# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Volnxebec
tagline:             'A Personal Website'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://github.com/volnxebec" target="_blank">@volnxebec</a>.'
url:                 http://volnxebec.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Volnxebec
  url:               https://github.com/volnxebec
  email:             volnxebec@yahoo.com

# Custom vars
version:             1.0.0
